title = "Prashansa Joshi"
baseURL = "https://prashansa-joshi.com.np/"
languageCode = "en-us"
theme = "hugo-PaperMod"
enableRobotsTXT = true

[params]
  author = "Prashansa Joshi"
  description = "DevOps Engineer | AWS Community Builder"
  home = "home-info"

[[params.social]]
  name = "GitHub"
  url = "https://github.com/prashansajoshi"

[[params.social]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/prashansa-joshi-268682230/"

[outputs]
  home = ["HTML", "RSS"]

[taxonomies]
  tag = "tags"
  category = "categories"

[pagination]
  pagerSize = 6

[[menu.main]]
  identifier = "blog"
  name = "Blog"
  url = "/blogs/"
  weight = 20
